### ISSUE TITLE
Can't download models

### ISSUE THREAD

**Issue by marloncarvalho** [synacktraa/swiftrank#1]
It cannot download the models anymore. I've noticed that FlashRank has changed the address where the files are located. SwiftRank uses the same address and it's now "deprecated". Possible solutions: host the models in an own address or update the code to reference the new location.

**Comment by PrithivirajDamodaran** [comment]
@synacktraa your library VOILATES the spirit of OSS Collaboration by reusing the cloud bucket of flashrank. Cloud buckets are NOT FREE !

The beauty of OSS is anyone is free to copy or repurpose permissively licensed code with attribution. 

But cloud buckets costs $ for storage, ingress and egress. 

One cannot claim innocence or ignorance for an attempt like this. A rewrite version pointing to someone else’s (org or individual) bucket amounts to stealing. 

Setup YOUR OWN BUCKET. Stop stealing. 

@marloncarvalho - You seem like a reasonable person. How are you even suggesting an option to point to the new location ?

**Comment by marloncarvalho** [comment]
Hi @PrithivirajDamodaran. I don't really know what's the best solution here. I found SwiftRank after using FlashRank for a few days. I've noticed that SwiftRank has better performance and doens't crash my container (2gb of ram) when reranking 100 or more documents. That's the reason why I switched from FlashRank to SwiftRank.

At first, I didn't know it was using FlashRank storage. I just realized it when it stopped working. I didn't know this storage costs money either and that's why suggested updating the code to point to the new location. However, it seems clear now that's not the way to go.

Is there any problem hosting the same files you have from other storage? Just asking, I don't really know if there's any implications in this case.

**Comment by PrithivirajDamodaran** [comment]
@marloncarvalho why are you mixing things here. 1st things 1st - Shouldn't the author have the professional courtesy to first discuss this with me ? 

2nd thing, Flashrank is used in production by many users, including myself. if you have questions about that this isn't the right forum open up an issue there.

**Comment by marloncarvalho** [comment]
@PrithivirajDamodaran sorry, I didn't make myself clear. I wasn't trying to "open an issue" here. I was just trying to clarify things and make it clear I wasn't one of the authors as it may have looked like in my first post.

Yes, you're totally right. If you have costs to store the files, there's no doubt SwiftRank's author should have asked your permission beforehand.

**Comment by PrithivirajDamodaran** [comment]
@marloncarvalho - Absolutely no confusion here, I did not mistake you for an author, 

As you mentioned your challenge below

> I've noticed that SwiftRank has better performance and doens't crash my container (2gb of ram) when reranking 100 or more documents. That's the reason why I switched from FlashRank to SwiftRank.

I was telling you this isn't the right forum to discuss the challenges you faced. Feel free to open an issue, If you did open I will be happy to help. 

But thats NOT the main idea of my commenting in this thread.

**Comment by marloncarvalho** [comment]
Agreed. Let's focus on the main problem here. :-) 

@synacktraa Could you host your own files on your own storage?

@PrithivirajDamodaran Is there any copyright restriction in your model files? Can it be downloaded and reused?

**Comment by synacktraa** [comment]
> @synacktraa your library VOILATES the spirit of OSS Collaboration by reusing the cloud bucket of flashrank. Cloud buckets are NOT FREE !
> 
> The beauty of OSS is anyone is free to copy or repurpose permissively licensed code with attribution.
> 
> But cloud buckets costs $ for storage, ingress and egress.
> 
> One cannot claim innocence or ignorance for an attempt like this. A rewrite version pointing to someone else’s (org or individual) bucket amounts to stealing.
> 
> Setup YOUR OWN BUCKET. Stop stealing.
> 
> @marloncarvalho - You seem like a reasonable person. How are you even suggesting an option to point to the new location ?

Hi @PrithivirajDamodaran, I don't know what you mean by stealing here. I had no idea about that your hosted models were on cloud buckets. I did open open a PR improving some functionalities, but you never accepted it. Also I tried to follow as much as I could understand from the LICENSE you're using. I even gave acknowledgement to FlashRank project to help people understand that it's just a improved version and that I'm not the owner. Please don't use the word 'steal' so easily. Thankyou.

https://github.com/PrithivirajDamodaran/FlashRank/pull/4#issue-2034035479

**Comment by synacktraa** [comment]
> Agreed. Let's focus on the main problem here. :-)
> 
> @synacktraa Could you host your own files on your own storage?
> 
> @PrithivirajDamodaran Is there any copyright restriction in your model files? Can it be downloaded and reused?

Sorry man I'll just delete this repository, I'm a student and I don't want someone to sue me for something I'm not even aware of. I feel really bad that he used the word 'stealing', I had no intention like that. You should open this issue in original FlashRank library or If he does allows to host the models, you can do it yourself too. I have never worked with cloud buckets. Thankyou.

**Comment by marloncarvalho** [comment]
I'm really sad to hear that. You've made a great work here and I believe that you didn't want to steal anything. I think these are the same files you can download directly from HuggingFace repository. Maybe you could download from there. 

@synacktraa

**Comment by synacktraa** [comment]
> I'm really sad to hear that. You've made a great work here and I believe that you didn't want to steal anything. I think these are the same files you can download directly from HuggingFace repository. Maybe you could download from there.
> 
> @synacktraa

Oh is it available on HF? @marloncarvalho  I don't even understand why he said I stole it. Isn't it just downloading the model from there? It's not like swiftrank is using it for inferencing.

**Comment by marloncarvalho** [comment]
@synacktraa  He sad it because he's paying to host the files. I agree that you should've asked him but at the same time I believe that you didn't want to do any harm to him. Maybe just an e-mail asking to remove the reference to his storage would have easily solved this.

Not exactly the same files, but I think we can derive the files from HuggingFace repository. I'm not an expert about it. :-)

**Comment by synacktraa** [comment]
> @synacktraa He sad it because he's paying to host the files. I agree that you should've asked him but at the same time I believe that you didn't want to do any harm to him. Maybe just an e-mail asking to remove the reference to his storage would have easily solved this.
> 
> Not exactly the same files, but I think we can derive the files from HuggingFace repository. I'm not an expert about it. :-)

Thanks for understanding. I'll update and point the files to HF asap from my end.

**Comment by PrithivirajDamodaran** [comment]
@synacktraa - 

- Let's take it step by step.  Understand what transpired and how it impacts me.
- How did I come know this library is pointing to my bucket in the 1st place ? A small change in my overall cloud $, not much but enough to notice. I started digging from there.
-  **I am an individual using my hard earned money for writing OSS for the community, not a funded company or corporate.**
- As mentioned in the 1st comment, LICENSE is ONLY for the code not for the cloud bucket. Its a common knowledge.
- "I had no idea about that your hosted models were on cloud buckets" - Please ask me, you are also connected with me in LinkedIn apparently recently. You never DMed me or anything. When in doubt always reach and out ask.
- If your PR was not merged doesn't you give the authority to point someone else's $ bucket without asking.
- If you use something that **I am paying ($) for without me knowing or telling me what else it is called** ? 
- Exact phrase I used "Setup YOUR OWN BUCKET. Stop stealing." Stealing is used in the conjunction with the CLOUD BUCKET $ that your library's model downloads is costing me. Data egress. It can be pennies on the dollar but on an aggregate it can pile-up. 
- No, int8 Quantised models are not available directly in HF, if it did Wouldn't I have not pointed it directly there in the 1st place ? Why will I take is effort ? 
- Exporting models aren't always straight-forward, for some models like Flan-T5 we need to write custom code. 
- I have trained and uploaded multiple models with 22M+ model downloads in HF. I never have to claim ownership to someone else model files. Thats what the phrase "Based on SoTA cross encoder models..." in flashrank desc means.

@marloncarvalho - 

If you are using someone else's work the burden and responsibility is on you to reach out for clarification and help. How many people I can email like this "please don't abuse or steal my resources its costing me $" ?. The author is also connected with me in LinkedIn apparently very recently. 

Just because it serves your purpose don't make claims like this. 

----

I love the spirit of open source and I have been doing this for a long time now. To prevent further abuse of myself and my cloud bucket $ and solve this issue, I can upload the int8 models to HF and let you know. 

You can reuse it.

**Comment by marloncarvalho** [comment]
@PrithivirajDamodaran You have a point and I understand it. However, don't get me wrong, I think you overreacted, mainly because you said he was stealing you. You even changed FlashRank's readme to say you were stoled. It sounded like he did it to cause harm to you and I believe that was not the case. 

And yes, I can make claims like this one, don't tell me what I can or cannot do. I said it because I think it would've be solved in a better way. That's how I think and that's okay. You think differently than me but I don't tell you what you can or cannot say.

But there's no point in keeping this discussion. @synacktraa already told he will point to another repository and it's useless to keep this discussion.

**Comment by PrithivirajDamodaran** [comment]
@marloncarvalho - I did not react at all :-) I responded and moved step by step. 1st I created a new bucket, moved my contents to prevent further issues. Only because of it you noticed download problems and created the issue. Only then I responded to this issue, where is the overreaction here ?

How would you have responded if you have to pay extra cloud bill because of a wrongful situation like this ?

If you are taking that stand. I can respond the way I see fit when it comes to my money and my resources.  You most certainly don't get to tell me about it or how should engage with them. Also even after hinting that the author should talk to me, you started negotiating on behalf of the author, which you have no business to do.

>As promised, Here is new link:  https://huggingface.co/prithivida/flashrank and it is covered under cc-by-sa-4.0 license for source attribution.

Enjoy.

**Comment by marloncarvalho** [comment]
@PrithivirajDamodaran  Really? Your first move was to change your bucket address. That's okay, I'd have done it too. Your second move: spread to the world that @synacktraa is a stealer. And you still think it's not overreacting? 

I would have responded asking him if he knows what he's doing. If he understands that he's wrong but never ever telling to everyone in the world that his a stealer. It's overreacting.

I'm "negotiating in behalf" of him because of your overreaction. He was thinking in deleting this repo because of it and I believe he should'nt do this. He made a mistake and he's willing to solve it. That's why I'm ready to help him.

**Comment by PrithivirajDamodaran** [comment]
@marloncarvalho - We all understand the value of a benefit of doubt and I also would have given it to a lay person but I understood that the author is competent in both ML (especially compressed models like GGUF) and Cyber security space (see below). 

Btw If I really wanted to spread, I have a good social capital (30k) and connections I could have easily created a social post to spread, not here in GitHub. I just notified my users in the repo because of this disruption people started facing problems and creating issues.

> Like I said when working with other's work and when in doubt always best to ask first.

I totally also understand your fear of losing a library that you are using and I see why you are taking his side and helping him. That's ok. It's human nature. 

I have shared the link to the int8 models. 



<img width="350" alt="Screenshot 2024-03-19 at 8 36 46 AM" src="https://github.com/synacktraa/swiftrank/assets/7071019/c724ff2d-6c03-4eb9-b810-40a6ee18cf89">

**Comment by maruthiprithivi** [comment]
As a production user of FlashRank, I feel the need to share my thoughts in this thread. Anyone familiar with the cloud would know that hosting a piece of data costs money, and it doesn't stop there. It extends to ingress and egress. I find the thread lopsided, and I wonder why the author of the repo needs to notify others of the changes to his internal assets. @PrithivirajDamodaran, as a beneficiary of your repo, I want to thank you for your work and support in your decision to make this change.

**Comment by maruthiprithivi** [comment]
...not to mention the dirstuption this has caused me and other existing users of FlashRank. 😓

**Comment by synacktraa** [comment]
@marloncarvalho Thanks so much for all your support. I'm going to update swiftrank with HF hosted models and incorporate some new minor functionalities. 

@PrithivirajDamodaran, thank you for uploading the models to HF. If there are any remaining concerns, please feel free to open an issue or contact me directly on LinkedIn. I would greatly appreciate it if any discrepancies were viewed as misunderstandings or lack of experience rather than intentional wrongdoing.

@maruthiprithivi Apologies for the inconvenience experienced by you and other FlashRank users. Thank you.

**Comment by marloncarvalho** [comment]
@synacktraa I think there's no need to keep this issue open anymore. Closing it.
